#!/bin/bash

Cputemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
Cputemp1=$(($Cputemp0/1000))
Cputemp2=$(($Cputemp0-($Cputemp1*1000)))
Cputemp3=$(($Cputemp2/10))
Cpufreq0=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
Cpufreq1=$(($Cpufreq0/1000000))
Cpufreq2=$(($Cpufreq0-($Cpufreq1*1000000)))
Cpufreq3=$(($Cpufreq2/10000))
hostname=$(hostname)



echo  Hostname: $hostname
echo  ____________________________
echo  CPU temperature "= $Cputemp1,$Cputemp3 C°"
echo  CPU frequency "= $Cpufreq1,$Cpufreq3 GHz"
